name: papermc

services:
  papermc:
    image: itzg/minecraft-server:latest # https://docker-minecraft-server.readthedocs.io
    container_name: papermc
    restart: unless-stopped
    pull_policy: daily
    tty: true
    stdin_open: true
    ports:
      - "8100:8100"
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - ./data:/data
      - ./icon.png:/icon.png
    environment:
      UID: ${UID}
      GID: ${GID}
      MEMORY: "4096M"
      TYPE: "PAPER"
      VERSION: ${VERSION:-latest}
      EULA: "TRUE"
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      LEVEL: "world-2026"
      ICON: /icon.png
      OVERRIDE_ICON: true
      ENABLE_WHITELIST: "true"
      WHITELIST: ${WHITELIST}
      OPS: ${OPS}
      MOTD: ${MOTD}
      DIFFICULTY: ${DIFFICULTY}
      MODRINTH_PROJECTS: |
        viaversion
        viabackwards
        vaultunlocked
        luckperms
        essentialsx
        essentialsx-spawn
        multiverse-core
        multiverse-netherportals
        multiverse-signportals
        bluemap
        worldedit

  papermcbackup:
    image: itzg/mc-backup # https://github.com/itzg/docker-mc-backup
    container_name: papermc_backup
    restart: unless-stopped
    depends_on:
      papermc:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data:ro
      - ./backups:/backups
      - ./rclone.conf:/config/rclone/rclone.conf:ro
    environment:
      SRC_DIR: /data
      DEST_DIR: /backups
      RCON_HOST: papermc
      BACKUP_METHOD: "rclone"
      PRUNE_BACKUPS_DAYS: 20
      NAME_WITH_VERSION: true
      RCLONE_REMOTE: "mcbackup-sftp"
      RCLONE_DEST_DIR: ${RCLONE_DEST_DIR}
      EXCLUDES: "bluemap"
      CRON_SCHEDULE: "0 4 * * *"
      CRON_BACKUP_UID: ${UID}
