name: papermc

services:
  papermc:
    image: itzg/minecraft-server:latest # https://docker-minecraft-server.readthedocs.io
    container_name: papermc
    restart: unless-stopped
    pull_policy: daily
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    environment:
      UID: ${UID}
      GID: ${GID}
      MEMORY: "4096M"
      TYPE: "PAPER"
      EULA: "TRUE"
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      LEVEL: "world-2026"
      MODRINTH_PROJECTS: |
        viaversion
        viabackwards
        vaultunlocked
        essentialsx
        essentialsx-spawn

      # Disabled modrinth projects
      # geyser