name: syncthing

services:
  syncthing:
    image: syncthing/syncthing # https://github.com/syncthing/syncthing/blob/main/README-Docker.md
    container_name: syncthing
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${MOUNT_POINT}:/var/syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - STGUIADDRESS=
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
